// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VivoApi.Data;

namespace VivoApi.Migrations
{
  [DbContext(typeof(ApplicationDbContext))]
  [Migration("20200605144559_createPasswordHash")]
  partial class createPasswordHash
  {
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
      modelBuilder
          .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
          .HasAnnotation("ProductVersion", "3.1.4")
          .HasAnnotation("Relational:MaxIdentifierLength", 63);

      modelBuilder.Entity("VivoApi.Entities.Users", b =>
          {
            b.Property<long>("Id")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("bigint")
                      .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            b.Property<string>("Cpf")
                      .HasColumnType("text");

            b.Property<string>("LastName")
                      .HasColumnType("text");

            b.Property<string>("Name")
                      .HasColumnType("text");

            b.Property<byte[]>("PasswordHash")
                      .HasColumnType("bytea");



            b.HasKey("Id");

            b.ToTable("Users");
          });
#pragma warning restore 612, 618
    }
  }
}
